#Docker Compose is a tool that was developed to help define and share multi-container applications
#Note that Docker Compose need to be installed.
# HOW TO RUN::
# docker-compose up -d
# That's all..go to localhost:3005...

version: "3.8" 

services:
        app: #service entry
            image: node:12-alpine
            command: sh -c "yarn install && yarn run dev"
            ports:
                - 3005:3000
            working_dir: /app
            volumes:
                - ./:/app
            environment:
                MYSQL_HOST: mysql
                MYSQL_USER: root
                MYSQL_PASSWORD: secret
                MYSQL_DB: todos
        mysql:
            image: mysql:5.7
            volumes:
                - todo-mysql-data:/var/lib/mysql
            environment: 
                MYSQL_ROOT_PASSWORD: secret
                MYSQL_DATABASE: todos
volumes:
    todo-mysql-data: